[project]
name = "next-layer-sae"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "torch>=2.9.1",
]
version = "0.0.0"

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]
